spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/subject_db
spring.datasource.username=postgres
spring.datasource.password=5927

# Mybatis接続設定
mybatis.mapper-locations=classpath:com/example/demo/dao/*.xml
mybatis.type-aliases-package=com.example.demo.entity
mybatis.configuration.map-underscore-to-camel-case=true