spring.application.name=6-8

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ec_order_db
spring.datasource.username=postgres
spring.datasource.password=5927

# MyBatis
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.example.ecorder.entity

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080