# PostgreSQL接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/study_db
spring.datasource.username=postgres
spring.datasource.password=5927

# PostgreSQLドライバ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA設定
spring.jpa.hibernate.ddl-auto=update

# SQL表示
spring.jpa.show-sql=true

# SQL整形表示
spring.jpa.properties.hibernate.format_sql=true

# Thymeleafキャッシュ無効
spring.thymeleaf.cache=false

# 日本語文字化け対策
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# アプリ再起動なしで反映
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true