spring.application.name=EcOrderApp
spring.datasource.url=jdbc:postgresql://localhost:5432/ec_order_db
spring.datasource.username=postgres
spring.datasource.password=5927

mybatis.mapper-locations=classpath:/mapper/*.xml